//
// InstitutionSupportedNetworks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Contains the RTP network and types supported by the linked Item&#39;s institution. */
public struct InstitutionSupportedNetworks: Codable, JSONEncodable, Hashable {

    public var rtp: TransferCapabilitiesGetRTP

    public init(rtp: TransferCapabilitiesGetRTP) {
        self.rtp = rtp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rtp
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rtp, forKey: .rtp)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        rtp = try container.decode(TransferCapabilitiesGetRTP.self, forKey: .rtp)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("rtp")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

