//
// InvestmentHoldingsGetRequestOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An optional object to filter &#x60;/investments/holdings/get&#x60; results. If provided, must not be &#x60;null&#x60;. */
public struct InvestmentHoldingsGetRequestOptions: Codable, JSONEncodable, Hashable {

    /** An array of `account_id`s to retrieve for the Item. An error will be returned if a provided `account_id` is not associated with the Item. */
    public var accountIds: [String]?

    public init(accountIds: [String]? = nil) {
        self.accountIds = accountIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountIds = "account_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountIds, forKey: .accountIds)
    }
}

