//
// LinkTokenCreateCardSwitch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A map containing data to pass in for the Card Switch flow. */
public struct LinkTokenCreateCardSwitch: Codable, JSONEncodable, Hashable {

    /** The BIN (Bank Identification Number) of the card to switch. */
    public var cardBin: String

    public init(cardBin: String) {
        self.cardBin = cardBin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cardBin = "card_bin"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cardBin, forKey: .cardBin)
    }
}

