//
// NumbersInternational.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Identifying information for transferring money to or from an international bank account via wire transfer. */
public struct NumbersInternational: Codable, JSONEncodable, Hashable {

    /** The Plaid account ID associated with the account numbers */
    public var accountId: String
    /** The International Bank Account Number (IBAN) for the account */
    public var iban: String
    /** The Bank Identifier Code (BIC) for the account */
    public var bic: String

    public init(accountId: String, iban: String, bic: String) {
        self.accountId = accountId
        self.iban = iban
        self.bic = bic
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId = "account_id"
        case iban
        case bic
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accountId, forKey: .accountId)
        try container.encode(iban, forKey: .iban)
        try container.encode(bic, forKey: .bic)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        accountId = try container.decode(String.self, forKey: .accountId)
        iban = try container.decode(String.self, forKey: .iban)
        bic = try container.decode(String.self, forKey: .bic)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("account_id")
        nonAdditionalPropertyKeys.insert("iban")
        nonAdditionalPropertyKeys.insert("bic")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

