//
// PartnerCustomerEnableResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response schema for &#x60;/partner/customer/enable&#x60;. */
public struct PartnerCustomerEnableResponse: Codable, JSONEncodable, Hashable {

    /** The end customer's secret key for the Production environment. */
    public var productionSecret: String?
    /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
    public var requestId: String?

    public init(productionSecret: String? = nil, requestId: String? = nil) {
        self.productionSecret = productionSecret
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productionSecret = "production_secret"
        case requestId = "request_id"
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(productionSecret, forKey: .productionSecret)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        productionSecret = try container.decodeIfPresent(String.self, forKey: .productionSecret)
        requestId = try container.decodeIfPresent(String.self, forKey: .requestId)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("production_secret")
        nonAdditionalPropertyKeys.insert("request_id")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

