//
// TransactionsUpdateStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A description of the update status for transaction pulls of an Item.  &#x60;TRANSACTIONS_UPDATE_STATUS_UNKNOWN&#x60;: Unable to fetch transactions update status for Item. &#x60;NOT_READY&#x60;: The Item is pending transaction pull. &#x60;INITIAL_UPDATE_COMPLETE&#x60;: Initial pull for the Item is complete, historical pull is pending. &#x60;HISTORICAL_UPDATE_COMPLETE&#x60;: Both initial and historical pull for Item are complete. */
public enum TransactionsUpdateStatus: String, Codable, CaseIterable {
    case transactionsUpdateStatusUnknown = "TRANSACTIONS_UPDATE_STATUS_UNKNOWN"
    case notReady = "NOT_READY"
    case initialUpdateComplete = "INITIAL_UPDATE_COMPLETE"
    case historicalUpdateComplete = "HISTORICAL_UPDATE_COMPLETE"
}
