//
// TransferStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The status of the transfer.  &#x60;pending&#x60;: A new transfer was created; it is in the pending state. &#x60;posted&#x60;: The transfer has been successfully submitted to the payment network. &#x60;settled&#x60;: Credits are available to be withdrawn or debits have been deducted from the Plaid linked account. &#x60;funds_available&#x60;: Funds from the transfer have been released from hold and applied to the ledger&#39;s available balance. (Only applicable to ACH debits.) &#x60;cancelled&#x60;: The transfer was cancelled by the client. &#x60;failed&#x60;: The transfer failed, no funds were moved. &#x60;returned&#x60;: A posted transfer was returned. */
public enum TransferStatus: String, Codable, CaseIterable {
    case pending = "pending"
    case posted = "posted"
    case settled = "settled"
    case fundsAvailable = "funds_available"
    case cancelled = "cancelled"
    case failed = "failed"
    case returned = "returned"
}
