//
// TransactionsRuleField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Transaction field for which the rule is defined. */
public enum TransactionsRuleField: String, Codable, CaseIterable {
    case transactionId = "TRANSACTION_ID"
    case name = "NAME"
}
