//
// WalletISOCurrencyCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An ISO-4217 currency code, used with e-wallets and transactions. */
public enum WalletISOCurrencyCode: String, Codable, CaseIterable {
    case gbp = "GBP"
    case eur = "EUR"
}
