//
// WatchlistScreeningEntityProgramGetRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request input for fetching an entity watchlist program */
public struct WatchlistScreeningEntityProgramGetRequest: Codable, JSONEncodable, Hashable {

    /** ID of the associated entity program. */
    public var entityWatchlistProgramId: String
    /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
    public var secret: String?
    /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
    public var clientId: String?

    public init(entityWatchlistProgramId: String, secret: String? = nil, clientId: String? = nil) {
        self.entityWatchlistProgramId = entityWatchlistProgramId
        self.secret = secret
        self.clientId = clientId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entityWatchlistProgramId = "entity_watchlist_program_id"
        case secret
        case clientId = "client_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(entityWatchlistProgramId, forKey: .entityWatchlistProgramId)
        try container.encodeIfPresent(secret, forKey: .secret)
        try container.encodeIfPresent(clientId, forKey: .clientId)
    }
}

