name: PlaidAPI
targets:
  PlaidAPI:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [PlaidAPI]
    info:
      path: ./Info.plist
      version: 2020-09-14_1.517.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
