//
// ActionState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Enum representing the state of the action/activity. */
public enum ActionState: String, Codable, CaseIterable {
    case unknown = "UNKNOWN"
    case attempt = "ATTEMPT"
    case success = "SUCCESS"
    case failure = "FAILURE"
    case skipped = "SKIPPED"
}
