//
// AssetTransactionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Asset Transaction Type. */
public enum AssetTransactionType: String, Codable, CaseIterable {
    case credit = "Credit"
    case debit = "Debit"
}
