//
// BankIncomeRefreshCompleteWebhook.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Fired when a refreshed bank income report has finished generating or failed to generate, triggered by calling &#x60;/credit/bank_income/refresh&#x60;. To get this webhook, subscribe via the [Dashboard](https://dashboard.plaid.com/developers/webhooks). */
public struct BankIncomeRefreshCompleteWebhook: Codable, JSONEncodable, Hashable {

    /** `INCOME` */
    public var webhookType: String
    /** `BANK_INCOME_REFRESH_COMPLETE` */
    public var webhookCode: String
    /** The `user_id` corresponding to the user the webhook has fired for. */
    public var userId: String
    public var result: BankIncomeRefreshCompleteResult
    public var environment: WebhookEnvironmentValues

    public init(webhookType: String, webhookCode: String, userId: String, result: BankIncomeRefreshCompleteResult, environment: WebhookEnvironmentValues) {
        self.webhookType = webhookType
        self.webhookCode = webhookCode
        self.userId = userId
        self.result = result
        self.environment = environment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case webhookType = "webhook_type"
        case webhookCode = "webhook_code"
        case userId = "user_id"
        case result
        case environment
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(webhookType, forKey: .webhookType)
        try container.encode(webhookCode, forKey: .webhookCode)
        try container.encode(userId, forKey: .userId)
        try container.encode(result, forKey: .result)
        try container.encode(environment, forKey: .environment)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        webhookType = try container.decode(String.self, forKey: .webhookType)
        webhookCode = try container.decode(String.self, forKey: .webhookCode)
        userId = try container.decode(String.self, forKey: .userId)
        result = try container.decode(BankIncomeRefreshCompleteResult.self, forKey: .result)
        environment = try container.decode(WebhookEnvironmentValues.self, forKey: .environment)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("webhook_type")
        nonAdditionalPropertyKeys.insert("webhook_code")
        nonAdditionalPropertyKeys.insert("user_id")
        nonAdditionalPropertyKeys.insert("result")
        nonAdditionalPropertyKeys.insert("environment")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

