//
// BankTransferEventListDirection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Indicates the direction of the transfer: &#x60;outbound&#x60;: for API-initiated transfers &#x60;inbound&#x60;: for payments received by the FBO account. */
public enum BankTransferEventListDirection: String, Codable, CaseIterable {
    case inbound = "inbound"
    case outbound = "outbound"
    case null = "null"
}
