//
// BeaconAccountRiskEvaluateAccount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An account in the &#x60;/beacon/account_risk/v1/evaluate&#x60; response. */
public struct BeaconAccountRiskEvaluateAccount: Codable, JSONEncodable, Hashable {

    /** The account ID. */
    public var accountId: String?
    public var type: AccountType?
    public var subtype: AccountSubtype?
    public var attributes: BeaconAccountRiskEvaluateAccountAttributes?

    public init(accountId: String? = nil, type: AccountType? = nil, subtype: AccountSubtype? = nil, attributes: BeaconAccountRiskEvaluateAccountAttributes? = nil) {
        self.accountId = accountId
        self.type = type
        self.subtype = subtype
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId = "account_id"
        case type
        case subtype
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(subtype, forKey: .subtype)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

