//
// CountryCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** ISO-3166-1 alpha-2 country code standard. */
public enum CountryCode: String, Codable, CaseIterable {
    case us = "US"
    case gb = "GB"
    case es = "ES"
    case nl = "NL"
    case fr = "FR"
    case ie = "IE"
    case ca = "CA"
    case de = "DE"
    case it = "IT"
    case pl = "PL"
    case dk = "DK"
    case no = "NO"
    case se = "SE"
    case ee = "EE"
    case lt = "LT"
    case lv = "LV"
    case pt = "PT"
    case be = "BE"
}
