//
// CraBankIncomeCompleteResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The result of the bank income report generation  &#x60;SUCCESS&#x60;: The bank income report was successfully generated and can be retrieved via &#x60;/cra/bank_income/get&#x60;.  &#x60;FAILURE&#x60;: The bank income report failed to be generated */
public enum CraBankIncomeCompleteResult: String, Codable, CaseIterable {
    case success = "SUCCESS"
    case failure = "FAILURE"
}
