//
// CraLoanOpenedStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Contains the status and date information of the loan when registering. */
public struct CraLoanOpenedStatus: Codable, JSONEncodable, Hashable {

    public var status: CraLoanStatus
    /** The effective date for the status of the loan. The date should be in ISO 8601 format (YYYY-MM-DD). */
    public var date: Date

    public init(status: CraLoanStatus, date: Date) {
        self.status = status
        self.date = date
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case date
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(date, forKey: .date)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        status = try container.decode(CraLoanStatus.self, forKey: .status)
        date = try container.decode(Date.self, forKey: .date)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("status")
        nonAdditionalPropertyKeys.insert("date")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

