//
// CreditSessionDocumentIncomeResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The details of a document income verification in Link */
public struct CreditSessionDocumentIncomeResult: Codable, JSONEncodable, Hashable {

    /** The number of paystubs uploaded by the user. */
    public var numPaystubsUploaded: Int
    /** The number of w2s uploaded by the user. */
    public var numW2sUploaded: Int
    /** The number of bank statements uploaded by the user. */
    public var numBankStatementsUploaded: Int
    /** The number of 1099s uploaded by the user */
    public var num1099sUploaded: Int

    public init(numPaystubsUploaded: Int, numW2sUploaded: Int, numBankStatementsUploaded: Int, num1099sUploaded: Int) {
        self.numPaystubsUploaded = numPaystubsUploaded
        self.numW2sUploaded = numW2sUploaded
        self.numBankStatementsUploaded = numBankStatementsUploaded
        self.num1099sUploaded = num1099sUploaded
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case numPaystubsUploaded = "num_paystubs_uploaded"
        case numW2sUploaded = "num_w2s_uploaded"
        case numBankStatementsUploaded = "num_bank_statements_uploaded"
        case num1099sUploaded = "num_1099s_uploaded"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(numPaystubsUploaded, forKey: .numPaystubsUploaded)
        try container.encode(numW2sUploaded, forKey: .numW2sUploaded)
        try container.encode(numBankStatementsUploaded, forKey: .numBankStatementsUploaded)
        try container.encode(num1099sUploaded, forKey: .num1099sUploaded)
    }
}

