//
// CreditSessionBankEmploymentStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Status of the Bank Employment Link session.  &#x60;APPROVED&#x60;: User has approved and verified their employment.  &#x60;NO_EMPLOYMENTS_FOUND&#x60;: We attempted, but were unable to find any employment in the connected account.  &#x60;EMPLOYER_NOT_LISTED&#x60;: The user explicitly indicated that they did not see their current or previous employer in the list of employer names found.  &#x60;STARTED&#x60;: The user began the bank income portion of the link flow.  &#x60;INTERNAL_ERROR&#x60;: The user encountered an internal error. */
public enum CreditSessionBankEmploymentStatus: String, Codable, CaseIterable {
    case approved = "APPROVED"
    case noEmployersFound = "NO_EMPLOYERS_FOUND"
    case employerNotListed = "EMPLOYER_NOT_LISTED"
}
