//
// CreditSessionBankIncomeStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Status of the Bank Income Link session.  &#x60;APPROVED&#x60;: User has approved and verified their income  &#x60;NO_DEPOSITS_FOUND&#x60;: We attempted, but were unable to find any income in the connected account.  &#x60;USER_REPORTED_NO_INCOME&#x60;: The user explicitly indicated that they don&#39;t receive income in the connected account.  &#x60;STARTED&#x60;: The user began the bank income portion of the link flow.  &#x60;INTERNAL_ERROR&#x60;: The user encountered an internal error. */
public enum CreditSessionBankIncomeStatus: String, Codable, CaseIterable {
    case approved = "APPROVED"
    case noDepositsFound = "NO_DEPOSITS_FOUND"
    case userReportedNoIncome = "USER_REPORTED_NO_INCOME"
}
