//
// CreditRelayRefreshRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** CreditRelayRefreshRequest defines the request schema for &#x60;/credit/relay/refresh&#x60; */
public struct CreditRelayRefreshRequest: Codable, JSONEncodable, Hashable {

    /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
    public var clientId: String?
    /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
    public var secret: String?
    /** The `relay_token` granting access to the report you would like to refresh. */
    public var relayToken: String
    public var reportType: ReportType
    /** The URL registered to receive webhooks when the report of a relay token has been refreshed. */
    public var webhook: String?

    public init(clientId: String? = nil, secret: String? = nil, relayToken: String, reportType: ReportType, webhook: String? = nil) {
        self.clientId = clientId
        self.secret = secret
        self.relayToken = relayToken
        self.reportType = reportType
        self.webhook = webhook
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId = "client_id"
        case secret
        case relayToken = "relay_token"
        case reportType = "report_type"
        case webhook
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(clientId, forKey: .clientId)
        try container.encodeIfPresent(secret, forKey: .secret)
        try container.encode(relayToken, forKey: .relayToken)
        try container.encode(reportType, forKey: .reportType)
        try container.encodeIfPresent(webhook, forKey: .webhook)
    }
}

