//
// DocumentStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An outcome status for this specific document submission. Distinct from the overall &#x60;documentary_verification.status&#x60; that summarizes the verification outcome from one or more documents. */
public enum DocumentStatus: String, Codable, CaseIterable {
    case success = "success"
    case failed = "failed"
    case manuallyApproved = "manually_approved"
}
