//
// EmploymentSourceType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The types of source employment data that users should be able to share */
public enum EmploymentSourceType: String, Codable, CaseIterable {
    case bank = "bank"
    case payroll = "payroll"
}
