//
// FDXContentTypes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Types of document formats. (Suggested values) */
public enum FDXContentTypes: String, Codable, CaseIterable {
    case applicationSlashPdf = "application/pdf"
    case imageSlashGif = "image/gif"
    case imageSlashJpeg = "image/jpeg"
    case imageSlashTiff = "image/tiff"
    case imageSlashPng = "image/png"
    case applicationSlashJson = "application/json"
}
