//
// FDXFiAttribute.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Financial Institution provider-specific attribute */
public struct FDXFiAttribute: Codable, JSONEncodable, Hashable {

    /** Name of attribute */
    public var name: String
    /** Value of attribute */
    public var value: String

    public init(name: String, value: String) {
        self.name = name
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(value, forKey: .value)
    }
}

