//
// FDXHateoasLinkAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** HTTP Method to use for the request */
public enum FDXHateoasLinkAction: String, Codable, CaseIterable {
    case _get = "GET"
    case post = "POST"
    case patch = "PATCH"
    case delete = "DELETE"
    case put = "PUT"
}
