//
// FDXNotificationPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Custom key-value pairs payload for a notification */
public struct FDXNotificationPayload: Codable, JSONEncodable, Hashable {

    /** ID for the origination entity related to the notification */
    public var id: String?
    public var idType: FDXNotificationPayloadIdType?
    public var customFields: [FDXFiAttribute]?

    public init(id: String? = nil, idType: FDXNotificationPayloadIdType? = nil, customFields: [FDXFiAttribute]? = nil) {
        self.id = id
        self.idType = idType
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case idType
        case customFields
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(idType, forKey: .idType)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

