//
// FinancialInstitutionInsights.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Insights surrounding external financial institution counterparties associated with a user. */
public struct FinancialInstitutionInsights: Codable, JSONEncodable, Hashable {

    /** Name of the financial institution counterparty. */
    public var name: String
    /** A unique, stable, Plaid-generated id that maps to the counterparty. */
    public var entityId: String?
    /** The website associated with the counterparty. */
    public var website: String?
    /** Associated accounts, detected based on the nature of transfers to/from this institution. */
    public var detectedAccounts: [DetectedAccount]

    public init(name: String, entityId: String? = nil, website: String?, detectedAccounts: [DetectedAccount]) {
        self.name = name
        self.entityId = entityId
        self.website = website
        self.detectedAccounts = detectedAccounts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case entityId = "entity_id"
        case website
        case detectedAccounts = "detected_accounts"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(entityId, forKey: .entityId)
        try container.encode(website, forKey: .website)
        try container.encode(detectedAccounts, forKey: .detectedAccounts)
    }
}

