//
// Form1099Type.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Form 1099 Type */
public enum Form1099Type: String, Codable, CaseIterable {
    case unknown = "FORM_1099_TYPE_UNKNOWN"
    case misc = "FORM_1099_TYPE_MISC"
    case k = "FORM_1099_TYPE_K"
}
