//
// IdentityMatchRequestOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An optional object to filter /identity/match results */
public struct IdentityMatchRequestOptions: Codable, JSONEncodable, Hashable {

    /** An array of `account_ids` to perform fuzzy match */
    public var accountIds: [String]?

    public init(accountIds: [String]? = nil) {
        self.accountIds = accountIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountIds = "account_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountIds, forKey: .accountIds)
    }
}

