//
// IdentityVerificationAutofillCreateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Autofill represents unverified customer information. This needs to be confirmed by the customer before using. */
public struct IdentityVerificationAutofillCreateResponse: Codable, JSONEncodable, Hashable {

    public var status: IdentityVerificationAutofillStatus
    public var user: IdentityVerificationAutofillUserData?
    /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
    public var requestId: String

    public init(status: IdentityVerificationAutofillStatus, user: IdentityVerificationAutofillUserData?, requestId: String) {
        self.status = status
        self.user = user
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case user
        case requestId = "request_id"
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(user, forKey: .user)
        try container.encode(requestId, forKey: .requestId)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        status = try container.decode(IdentityVerificationAutofillStatus.self, forKey: .status)
        user = try container.decodeIfPresent(IdentityVerificationAutofillUserData.self, forKey: .user)
        requestId = try container.decode(String.self, forKey: .requestId)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("status")
        nonAdditionalPropertyKeys.insert("user")
        nonAdditionalPropertyKeys.insert("request_id")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

