//
// IncomeOverride.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Specify payroll data on the account. */
public struct IncomeOverride: Codable, JSONEncodable, Hashable {

    /** A list of paystubs associated with the account. */
    public var paystubs: [PaystubOverride]?
    /** A list of w2s associated with the account. */
    public var w2s: [W2Override]?

    public init(paystubs: [PaystubOverride]? = nil, w2s: [W2Override]? = nil) {
        self.paystubs = paystubs
        self.w2s = w2s
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case paystubs
        case w2s
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(paystubs, forKey: .paystubs)
        try container.encodeIfPresent(w2s, forKey: .w2s)
    }
}

