//
// InvestmentsTransactionsGetRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** InvestmentsTransactionsGetRequest defines the request schema for &#x60;/investments/transactions/get&#x60; */
public struct InvestmentsTransactionsGetRequest: Codable, JSONEncodable, Hashable {

    /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
    public var clientId: String?
    /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
    public var secret: String?
    /** The access token associated with the Item data is being requested for. */
    public var accessToken: String
    /** The earliest date for which to fetch transaction history. Dates should be formatted as YYYY-MM-DD. */
    public var startDate: Date
    /** The most recent date for which to fetch transaction history. Dates should be formatted as YYYY-MM-DD. */
    public var endDate: Date
    public var options: InvestmentsTransactionsGetRequestOptions?

    public init(clientId: String? = nil, secret: String? = nil, accessToken: String, startDate: Date, endDate: Date, options: InvestmentsTransactionsGetRequestOptions? = nil) {
        self.clientId = clientId
        self.secret = secret
        self.accessToken = accessToken
        self.startDate = startDate
        self.endDate = endDate
        self.options = options
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId = "client_id"
        case secret
        case accessToken = "access_token"
        case startDate = "start_date"
        case endDate = "end_date"
        case options
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(clientId, forKey: .clientId)
        try container.encodeIfPresent(secret, forKey: .secret)
        try container.encode(accessToken, forKey: .accessToken)
        try container.encode(startDate, forKey: .startDate)
        try container.encode(endDate, forKey: .endDate)
        try container.encodeIfPresent(options, forKey: .options)
    }
}

