//
// ItemApplicationListUserAuth.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** User authentication parameters, for clients making a request without an &#x60;access_token&#x60;. This is only allowed for select clients and will not be supported in the future. Most clients should call /item/import to obtain an access token before making a request. */
public struct ItemApplicationListUserAuth: Codable, JSONEncodable, Hashable {

    /** Account username. */
    public var userId: String?
    /** Account username hashed by FI. */
    public var fiUsernameHash: String?

    public init(userId: String? = nil, fiUsernameHash: String? = nil) {
        self.userId = userId
        self.fiUsernameHash = fiUsernameHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId = "user_id"
        case fiUsernameHash = "fi_username_hash"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(fiUsernameHash, forKey: .fiUsernameHash)
    }
}

