//
// LinkTokenCreateRequestUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Specifies options for initializing Link for [update mode](https://plaid.com/docs/link/update-mode). */
public struct LinkTokenCreateRequestUpdate: Codable, JSONEncodable, Hashable {

    /** If `true`, enables [update mode with Account Select](https://plaid.com/docs/link/update-mode/#using-update-mode-to-request-new-accounts) for institutions that do not use OAuth, or that use OAuth but do not have their own account selection flow. For institutions that have an OAuth account selection flow (i.e. most OAuth-enabled institutions), update mode with Account Select will always be enabled, regardless of the value of this field. */
    public var accountSelectionEnabled: Bool? = false

    public init(accountSelectionEnabled: Bool? = false) {
        self.accountSelectionEnabled = accountSelectionEnabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountSelectionEnabled = "account_selection_enabled"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountSelectionEnabled, forKey: .accountSelectionEnabled)
    }
}

