//
// LinkDeliveryWebhookDeliveryStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The status of the delivery of the Hosted Link to the user */
public enum LinkDeliveryWebhookDeliveryStatus: String, Codable, CaseIterable {
    case success = "SUCCESS"
    case failure = "FAILURE"
}
