//
// LinkTokenCreateRequestPaymentInitiation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Specifies options for initializing Link for use with the Payment Initiation (Europe) product. This field is required if &#x60;payment_initiation&#x60; is included in the &#x60;products&#x60; array. Either &#x60;payment_id&#x60; or &#x60;consent_id&#x60; must be provided. */
public struct LinkTokenCreateRequestPaymentInitiation: Codable, JSONEncodable, Hashable {

    /** The `payment_id` provided by the `/payment_initiation/payment/create` endpoint. */
    public var paymentId: String?
    /** The `consent_id` provided by the `/payment_initiation/consent/create` endpoint. */
    public var consentId: String?

    public init(paymentId: String? = nil, consentId: String? = nil) {
        self.paymentId = paymentId
        self.consentId = consentId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case paymentId = "payment_id"
        case consentId = "consent_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(paymentId, forKey: .paymentId)
        try container.encodeIfPresent(consentId, forKey: .consentId)
    }
}

