//
// LinkDeliveryCommunicationMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The communication method containing both the type and address to send the URL. */
public struct LinkDeliveryCommunicationMethod: Codable, JSONEncodable, Hashable {

    public var method: LinkDeliveryDeliveryMethod?
    /** The phone number / email address that Hosted Link sessions are delivered to. Phone numbers must be in E.164 format. */
    public var address: String?

    public init(method: LinkDeliveryDeliveryMethod? = nil, address: String? = nil) {
        self.method = method
        self.address = address
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case method
        case address
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(method, forKey: .method)
        try container.encodeIfPresent(address, forKey: .address)
    }
}

