//
// LinkTokenCreateInstitutionData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A map containing data used to highlight institutions in Link. */
public struct LinkTokenCreateInstitutionData: Codable, JSONEncodable, Hashable {

    /** The routing number of the bank to highlight in Link. Note: in rare cases, a single routing number can be associated with multiple institutions, e.g. due to a brokerage using another institution to manage ACH on its sweep accounts. If this happens, the bank will not be highlighted in Link even if the routing number is provided. */
    public var routingNumber: String?

    public init(routingNumber: String? = nil) {
        self.routingNumber = routingNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case routingNumber = "routing_number"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(routingNumber, forKey: .routingNumber)
    }
}

