//
// PaymentInitiationAddress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The optional address of the payment recipient&#39;s bank account. Required by most institutions outside of the UK. */
public struct PaymentInitiationAddress: Codable, JSONEncodable, Hashable {

    static let cityRule = StringRule(minLength: 1, maxLength: 35, pattern: nil)
    static let postalCodeRule = StringRule(minLength: 1, maxLength: 16, pattern: nil)
    static let countryRule = StringRule(minLength: 2, maxLength: 2, pattern: nil)
    /** An array of length 1-2 representing the street address where the recipient is located. Maximum of 70 characters. */
    public var street: [String]
    /** The city where the recipient is located. Maximum of 35 characters. */
    public var city: String
    /** The postal code where the recipient is located. Maximum of 16 characters. */
    public var postalCode: String
    /** The ISO 3166-1 alpha-2 country code where the recipient is located. */
    public var country: String

    public init(street: [String], city: String, postalCode: String, country: String) {
        self.street = street
        self.city = city
        self.postalCode = postalCode
        self.country = country
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case street
        case city
        case postalCode = "postal_code"
        case country
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(street, forKey: .street)
        try container.encode(city, forKey: .city)
        try container.encode(postalCode, forKey: .postalCode)
        try container.encode(country, forKey: .country)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        street = try container.decode([String].self, forKey: .street)
        city = try container.decode(String.self, forKey: .city)
        postalCode = try container.decode(String.self, forKey: .postalCode)
        country = try container.decode(String.self, forKey: .country)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("street")
        nonAdditionalPropertyKeys.insert("city")
        nonAdditionalPropertyKeys.insert("postal_code")
        nonAdditionalPropertyKeys.insert("country")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

