//
// ProxyType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enum indicating whether a network proxy is present and if so what type it is.  &#x60;none_detected&#x60; indicates the user is not on a detectable proxy network.  &#x60;tor&#x60; indicates the user was using a Tor browser, which sends encrypted traffic on a decentralized network and is somewhat similar to a VPN (Virtual Private Network).  &#x60;vpn&#x60; indicates the user is on a VPN (Virtual Private Network)  &#x60;web_proxy&#x60; indicates the user is on a web proxy server, which may allow them to conceal information such as their IP address or other identifying information.  &#x60;public_proxy&#x60; indicates the user is on a public web proxy server, which is similar to a web proxy but can be shared by multiple users. This may allow multiple users to appear as if they have the same IP address for instance. */
public enum ProxyType: String, Codable, CaseIterable {
    case noneDetected = "none_detected"
    case tor = "tor"
    case vpn = "vpn"
    case webProxy = "web_proxy"
    case publicProxy = "public_proxy"
}
