//
// RecurringNewTransferWebhook.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Fired when a new transfer of a recurring transfer is originated. */
public struct RecurringNewTransferWebhook: Codable, JSONEncodable, Hashable {

    /** `TRANSFER` */
    public var webhookType: String
    /** `RECURRING_NEW_TRANSFER` */
    public var webhookCode: String
    /** Plaid’s unique identifier for a recurring transfer. */
    public var recurringTransferId: String
    /** Plaid’s unique identifier for a transfer. */
    public var transferId: String
    public var environment: WebhookEnvironmentValues

    public init(webhookType: String, webhookCode: String, recurringTransferId: String, transferId: String, environment: WebhookEnvironmentValues) {
        self.webhookType = webhookType
        self.webhookCode = webhookCode
        self.recurringTransferId = recurringTransferId
        self.transferId = transferId
        self.environment = environment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case webhookType = "webhook_type"
        case webhookCode = "webhook_code"
        case recurringTransferId = "recurring_transfer_id"
        case transferId = "transfer_id"
        case environment
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(webhookType, forKey: .webhookType)
        try container.encode(webhookCode, forKey: .webhookCode)
        try container.encode(recurringTransferId, forKey: .recurringTransferId)
        try container.encode(transferId, forKey: .transferId)
        try container.encode(environment, forKey: .environment)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        webhookType = try container.decode(String.self, forKey: .webhookType)
        webhookCode = try container.decode(String.self, forKey: .webhookCode)
        recurringTransferId = try container.decode(String.self, forKey: .recurringTransferId)
        transferId = try container.decode(String.self, forKey: .transferId)
        environment = try container.decode(WebhookEnvironmentValues.self, forKey: .environment)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("webhook_type")
        nonAdditionalPropertyKeys.insert("webhook_code")
        nonAdditionalPropertyKeys.insert("recurring_transfer_id")
        nonAdditionalPropertyKeys.insert("transfer_id")
        nonAdditionalPropertyKeys.insert("environment")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

