//
// ReportType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The report type. It can be &#x60;asset&#x60;. Income report types are not yet supported. */
public enum ReportType: String, Codable, CaseIterable {
    case asset = "asset"
}
