//
// RiskCheckEmailTopLevelDomainIsSuspicious.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Indicates whether the email address top level domain, which is the last part of the domain, is fraudulent or risky if known. In most cases, a suspicious top level domain is also associated with a disposable or high-risk domain. */
public enum RiskCheckEmailTopLevelDomainIsSuspicious: String, Codable, CaseIterable {
    case yes = "yes"
    case no = "no"
    case noData = "no_data"
}
