//
// RiskSignalDocumentReference.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Object containing metadata for the document */
public struct RiskSignalDocumentReference: Codable, JSONEncodable, Hashable {

    /** An identifier of the document referenced by the document metadata. */
    public var documentId: String?
    /** The name of the document */
    public var documentName: String?
    public var status: RiskSignalDocumentStatus?

    public init(documentId: String? = nil, documentName: String? = nil, status: RiskSignalDocumentStatus? = nil) {
        self.documentId = documentId
        self.documentName = documentName
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case documentId = "document_id"
        case documentName = "document_name"
        case status
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(documentId, forKey: .documentId)
        try container.encodeIfPresent(documentName, forKey: .documentName)
        try container.encodeIfPresent(status, forKey: .status)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        documentId = try container.decodeIfPresent(String.self, forKey: .documentId)
        documentName = try container.decodeIfPresent(String.self, forKey: .documentName)
        status = try container.decodeIfPresent(RiskSignalDocumentStatus.self, forKey: .status)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("document_id")
        nonAdditionalPropertyKeys.insert("document_name")
        nonAdditionalPropertyKeys.insert("status")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

