//
// SelfieStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An outcome status for this specific selfie. Distinct from the overall &#x60;selfie_check.status&#x60; that summarizes the verification outcome from one or more selfies. */
public enum SelfieStatus: String, Codable, CaseIterable {
    case success = "success"
    case failed = "failed"
}
