//
// ServiceProductFulfillment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A collection of details related to a fulfillment service or product in terms of request, process and result. */
public struct ServiceProductFulfillment: Codable, JSONEncodable, Hashable {

    public var SERVICE_PRODUCT_FULFILLMENT_DETAIL: ServiceProductFulfillmentDetail

    public init(SERVICE_PRODUCT_FULFILLMENT_DETAIL: ServiceProductFulfillmentDetail) {
        self.SERVICE_PRODUCT_FULFILLMENT_DETAIL = SERVICE_PRODUCT_FULFILLMENT_DETAIL
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case SERVICE_PRODUCT_FULFILLMENT_DETAIL
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(SERVICE_PRODUCT_FULFILLMENT_DETAIL, forKey: .SERVICE_PRODUCT_FULFILLMENT_DETAIL)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        SERVICE_PRODUCT_FULFILLMENT_DETAIL = try container.decode(ServiceProductFulfillmentDetail.self, forKey: .SERVICE_PRODUCT_FULFILLMENT_DETAIL)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("SERVICE_PRODUCT_FULFILLMENT_DETAIL")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

