//
// TaxpayerIdentifiers.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The collection of TAXPAYER_IDENTIFICATION elements */
public struct TaxpayerIdentifiers: Codable, JSONEncodable, Hashable {

    public var TAXPAYER_IDENTIFIER: TaxpayerIdentifier

    public init(TAXPAYER_IDENTIFIER: TaxpayerIdentifier) {
        self.TAXPAYER_IDENTIFIER = TAXPAYER_IDENTIFIER
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case TAXPAYER_IDENTIFIER
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(TAXPAYER_IDENTIFIER, forKey: .TAXPAYER_IDENTIFIER)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        TAXPAYER_IDENTIFIER = try container.decode(TaxpayerIdentifier.self, forKey: .TAXPAYER_IDENTIFIER)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("TAXPAYER_IDENTIFIER")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

