//
// TransferRecurringCreateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Defines the response schema for &#x60;/transfer/recurring/create&#x60; */
public struct TransferRecurringCreateResponse: Codable, JSONEncodable, Hashable {

    public var recurringTransfer: RecurringTransferNullable?
    public var decision: TransferAuthorizationDecision
    public var decisionRationale: TransferAuthorizationDecisionRationale?
    /** A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive. */
    public var requestId: String

    public init(recurringTransfer: RecurringTransferNullable? = nil, decision: TransferAuthorizationDecision, decisionRationale: TransferAuthorizationDecisionRationale? = nil, requestId: String) {
        self.recurringTransfer = recurringTransfer
        self.decision = decision
        self.decisionRationale = decisionRationale
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recurringTransfer = "recurring_transfer"
        case decision
        case decisionRationale = "decision_rationale"
        case requestId = "request_id"
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(recurringTransfer, forKey: .recurringTransfer)
        try container.encode(decision, forKey: .decision)
        try container.encodeIfPresent(decisionRationale, forKey: .decisionRationale)
        try container.encode(requestId, forKey: .requestId)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        recurringTransfer = try container.decodeIfPresent(RecurringTransferNullable.self, forKey: .recurringTransfer)
        decision = try container.decode(TransferAuthorizationDecision.self, forKey: .decision)
        decisionRationale = try container.decodeIfPresent(TransferAuthorizationDecisionRationale.self, forKey: .decisionRationale)
        requestId = try container.decode(String.self, forKey: .requestId)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("recurring_transfer")
        nonAdditionalPropertyKeys.insert("decision")
        nonAdditionalPropertyKeys.insert("decision_rationale")
        nonAdditionalPropertyKeys.insert("request_id")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

