//
// TransferBalanceGetRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Defines the request schema for &#x60;/transfer/balance/get&#x60; */
public struct TransferBalanceGetRequest: Codable, JSONEncodable, Hashable {

    /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
    public var clientId: String?
    /** Client ID of the end customer. */
    @available(*, deprecated, message: "This property is deprecated.")
    public var originatorClientId: String?
    /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
    public var secret: String?
    public var type: TransferBalanceType?

    public init(clientId: String? = nil, originatorClientId: String? = nil, secret: String? = nil, type: TransferBalanceType? = nil) {
        self.clientId = clientId
        self.originatorClientId = originatorClientId
        self.secret = secret
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId = "client_id"
        case originatorClientId = "originator_client_id"
        case secret
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(clientId, forKey: .clientId)
        try container.encodeIfPresent(originatorClientId, forKey: .originatorClientId)
        try container.encodeIfPresent(secret, forKey: .secret)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

