//
// TransferDocumentPurpose.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Specifies the purpose of the uploaded file.  &#x60;\&quot;DUE_DILIGENCE\&quot;&#x60; - The transfer due diligence document of the originator. */
public enum TransferDocumentPurpose: String, Codable, CaseIterable {
    case dueDiligence = "DUE_DILIGENCE"
}
