//
// TransferSweepStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The status of the sweep for the transfer.  &#x60;unswept&#x60;: The transfer hasn&#39;t been swept yet. &#x60;swept&#x60;: The transfer was swept to the sweep account. &#x60;swept_settled&#x60;: Credits are available to be withdrawn or debits have been deducted from the customer’s business checking account. &#x60;return_swept&#x60;: The transfer was returned, funds were pulled back or pushed back to the sweep account. &#x60;null&#x60;: The transfer will never be swept (e.g. if the transfer is cancelled or returned before being swept) */
public enum TransferSweepStatus: String, Codable, CaseIterable {
    case null = "null"
    case unswept = "unswept"
    case swept = "swept"
    case sweptSettled = "swept_settled"
    case returnSwept = "return_swept"
}
