//
// TransferEventListRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Defines the request schema for &#x60;/transfer/event/list&#x60; */
public struct TransferEventListRequest: Codable, JSONEncodable, Hashable {

    static let countRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 25, exclusiveMaximum: false, multipleOf: nil)
    static let offsetRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
    public var clientId: String?
    /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
    public var secret: String?
    /** The start datetime of transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`) */
    public var startDate: Date?
    /** The end datetime of transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`) */
    public var endDate: Date?
    /** Plaid’s unique identifier for a transfer. */
    public var transferId: String?
    /** The account ID to get events for all transactions to/from an account. */
    public var accountId: String?
    public var transferType: TransferEventListTransferType?
    /** Filter events by event type. */
    public var eventTypes: [TransferEventType]?
    /** Plaid’s unique identifier for a sweep. */
    public var sweepId: String?
    /** The maximum number of transfer events to return. If the number of events matching the above parameters is greater than `count`, the most recent events will be returned. */
    public var count: Int? = 25
    /** The offset into the list of transfer events. When `count`=25 and `offset`=0, the first 25 events will be returned. When `count`=25 and `offset`=25, the next 25 events will be returned. */
    public var offset: Int? = 0
    /** The origination account ID to get events for transfers from a specific origination account. */
    @available(*, deprecated, message: "This property is deprecated.")
    public var originationAccountId: String?
    /** Filter transfer events to only those with the specified originator client. */
    public var originatorClientId: String?
    /** Filter transfer events to only those with the specified `funding_account_id`. */
    public var fundingAccountId: String?

    public init(clientId: String? = nil, secret: String? = nil, startDate: Date? = nil, endDate: Date? = nil, transferId: String? = nil, accountId: String? = nil, transferType: TransferEventListTransferType? = nil, eventTypes: [TransferEventType]? = nil, sweepId: String? = nil, count: Int? = 25, offset: Int? = 0, originationAccountId: String? = nil, originatorClientId: String? = nil, fundingAccountId: String? = nil) {
        self.clientId = clientId
        self.secret = secret
        self.startDate = startDate
        self.endDate = endDate
        self.transferId = transferId
        self.accountId = accountId
        self.transferType = transferType
        self.eventTypes = eventTypes
        self.sweepId = sweepId
        self.count = count
        self.offset = offset
        self.originationAccountId = originationAccountId
        self.originatorClientId = originatorClientId
        self.fundingAccountId = fundingAccountId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId = "client_id"
        case secret
        case startDate = "start_date"
        case endDate = "end_date"
        case transferId = "transfer_id"
        case accountId = "account_id"
        case transferType = "transfer_type"
        case eventTypes = "event_types"
        case sweepId = "sweep_id"
        case count
        case offset
        case originationAccountId = "origination_account_id"
        case originatorClientId = "originator_client_id"
        case fundingAccountId = "funding_account_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(clientId, forKey: .clientId)
        try container.encodeIfPresent(secret, forKey: .secret)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(endDate, forKey: .endDate)
        try container.encodeIfPresent(transferId, forKey: .transferId)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encodeIfPresent(transferType, forKey: .transferType)
        try container.encodeIfPresent(eventTypes, forKey: .eventTypes)
        try container.encodeIfPresent(sweepId, forKey: .sweepId)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(offset, forKey: .offset)
        try container.encodeIfPresent(originationAccountId, forKey: .originationAccountId)
        try container.encodeIfPresent(originatorClientId, forKey: .originatorClientId)
        try container.encodeIfPresent(fundingAccountId, forKey: .fundingAccountId)
    }
}

