//
// WalletTransactionListRequestOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Additional wallet transaction options */
public struct WalletTransactionListRequestOptions: Codable, JSONEncodable, Hashable {

    /** Timestamp in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DDThh:mm:ssZ) for filtering transactions, inclusive of the provided date. */
    public var startTime: Date?
    /** Timestamp in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DDThh:mm:ssZ) for filtering transactions, inclusive of the provided date. */
    public var endTime: Date?

    public init(startTime: Date? = nil, endTime: Date? = nil) {
        self.startTime = startTime
        self.endTime = endTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startTime = "start_time"
        case endTime = "end_time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(startTime, forKey: .startTime)
        try container.encodeIfPresent(endTime, forKey: .endTime)
    }
}

