//
// WebhookVerificationKeyGetRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** WebhookVerificationKeyGetRequest defines the request schema for &#x60;/webhook_verification_key/get&#x60; */
public struct WebhookVerificationKeyGetRequest: Codable, JSONEncodable, Hashable {

    /** Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body. */
    public var clientId: String?
    /** Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body. */
    public var secret: String?
    /** The key ID ( `kid` ) from the JWT header. */
    public var keyId: String

    public init(clientId: String? = nil, secret: String? = nil, keyId: String) {
        self.clientId = clientId
        self.secret = secret
        self.keyId = keyId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId = "client_id"
        case secret
        case keyId = "key_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(clientId, forKey: .clientId)
        try container.encodeIfPresent(secret, forKey: .secret)
        try container.encode(keyId, forKey: .keyId)
    }
}

